import './globals.css'
import { Montserrat } from 'next/font/google'

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  weight: '500',
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
